GET http://localhost:3000/api/loans HTTP/1.1

###

GET http://localhost:3000/api/loans/692d9c3fdab373b92093782a HTTP/1.1

###

GET http://localhost:3000/api/loans/compare/24 HTTP/1.1

###

PUT http://localhost:3000/api/loans/6936d8558c934e5dce17bd6b HTTP/1.1
content-type: application/json

{
    "name":"raj",
    "email":"ssad@g.com",
    "panNumber":4547444447,
    "address":"sasdsd"
}

###

DELETE http://localhost:3000/api/loans/692d9668a364a8a2e490d225 HTTP/1.1